### ISSUE TITLE
Feature Request: Change TitleImage.xbx to something besides Xbox Softmodding Tool

### ISSUE THREAD

**Issue by Natetronn** [insignia-live/setup-assistant-release#2]
Consider changing the gamesave TitleImage.xbe image from Xbox Softmodding Tool to something indicative of Insignia Setup Assistant.

I just ran into an issue where I thought someone had installed Xbox Softmodding Tool instead of Insignia, as both were being discussed and as the Setup Assistant is using the Xbox Softmodding Tool's image instead of one of its own, this led to some confusion. 

I realize this is super low on the totem pole and kind of after the fact at this point, but figured it didn't hurt to request it, since it may also be an easy enough fix. 

To make it easier, I created and am attaching a new TitleImage.xbx. It includes your logo, your text color (taken from logo) and your background color (taken from website card background color.) I'm happy to make any adjustments, if need be.

[TitleImage.xbx.zip](https://github.com/insignia-live/setup-assistant-release/files/9923267/TitleImage.xbx.zip)

![TitleImage.xbx](https://user-images.githubusercontent.com/582149/199575390-2d810ad3-08b1-4596-aa29-3b284da4cac6.jpg)

**Comment by InternalLoss** [comment]
Fixed as of private PR #22
